### ISSUE TITLE
Load data from memory?

### ISSUE THREAD

**Issue by tostercx** [abbaye/WPFHexEditorControl#1]
Hey, awesome project! :)

Is it possible to load data from memory (byte[] or string)?
I only found methods to load from files.

**Comment by abbaye** [comment]
For now it's only possible with file but if you need this i can work on this

Le 22 janv. 2017 19:12, "tostercx" <notifications@github.com> a écrit :

Hey, awesome project :)

Is it possible to load data from memory (byte[] or string)?
I only found methods to load from files.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/abbaye/WPFHexEditorControl/issues/1>, or mute the thread

**Comment by abbaye** [comment]
Thank for good comment :)

I build this project for fun when i am watching tv lol

**Comment by abbaye** [comment]
It's work

You can now use memorystream in wpf hexaeditor

Use stream property

Update from github

Regards

Le 22 janv. 2017 19:17, "Derek Tremblay" <derektremblay666@gmail.com> a
écrit :

> Thank for good comment :)
>
> I build this project for fun when i am watching tv lol
>

**Comment by abbaye** [comment]
It's work

You can now use memorystream in wpf hexaeditor

Use stream property

Update from github

Regards

**Comment by tostercx** [comment]
OMG so fast! Thank you!!!

**Comment by abbaye** [comment]
It's work fine but not reload thé stream alternative save... i will work on
this late this week


Regards
