### ISSUE TITLE
Can I use this in C# Winforms

### ISSUE THREAD

**Issue by KaustubhPatange** [abbaye/WpfHexEditorControl#17]
So, I have read all readme and used your DLL in wpf forms. Appreciated your work! 

So my question is, Can I use this dll in C# Winforms?

**Comment by abbaye** [comment]
Hi Kaustubh,

Yes you can use the hexeditor in Winform application. 

Take the lastest code on github I have made a winform sample for you.

Thank for support ! :)

**Comment by KaustubhPatange** [comment]
Thanks you Sir! Soon gonna check that out!:blush:

**Comment by abbaye** [comment]
Give me a feedback if anything else :)

**Comment by KaustubhPatange** [comment]
Sure!

**Comment by abbaye** [comment]
Winform sample created ! :)

**Comment by KaustubhPatange** [comment]
Hello, I cloned your sample again. Now its giving me Error while compiling. Here is an attachment of this! It says its Read Only File, but the thing is Attributes are Normal

![attach](https://user-images.githubusercontent.com/22119598/33240828-b7ed0782-d2e2-11e7-8181-c3309e4c82e9.png)

**Comment by abbaye** [comment]
Oups i Will check this in one hours... sorry.for inconvenient 

Envoyé de mon appareil Samsung de Bell via le réseau le plus vaste au pays.
-------- Message d'origine --------De : Kaustubh Patange <notifications@github.com> Date : 17-11-26  09:18  (GMT-05:00) À : abbaye/WpfHexEditorControl <WpfHexEditorControl@noreply.github.com> Cc : Derek Tremblay <derektremblay666@gmail.com>, State change <state_change@noreply.github.com> Objet : Re: [abbaye/WpfHexEditorControl] Can I use this in C# Winforms (#17) 
Hello, I cloned your sample again. Now its giving me Error while compiling. Here is an attachment of this! It says its Read Only File, but the thing is Attributes are Normal



—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/abbaye/WpfHexEditorControl","title":"abbaye/WpfHexEditorControl","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/abbaye/WpfHexEditorControl"}},"updates":{"snippets":[{"icon":"PERSON","message":"@KaustubhPatange in #17: Hello, I cloned your sample again. Now its giving me Error while compiling. Here is an attachment of this! It says its Read Only File, but the thing is Attributes are Normal\r\n\r\n![attach](https://user-images.githubusercontent.com/22119598/33240828-b7ed0782-d2e2-11e7-8181-c3309e4c82e9.png)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/abbaye/WpfHexEditorControl/issues/17#issuecomment-347011691"}}}

**Comment by abbaye** [comment]
Are you cleaning solution before compile ??




Envoyé de mon appareil Samsung de Bell via le réseau le plus vaste au pays.
-------- Message d'origine --------De : Kaustubh Patange <notifications@github.com> Date : 17-11-26  09:18  (GMT-05:00) À : abbaye/WpfHexEditorControl <WpfHexEditorControl@noreply.github.com> Cc : Derek Tremblay <derektremblay666@gmail.com>, State change <state_change@noreply.github.com> Objet : Re: [abbaye/WpfHexEditorControl] Can I use this in C# Winforms (#17) 
Hello, I cloned your sample again. Now its giving me Error while compiling. Here is an attachment of this! It says its Read Only File, but the thing is Attributes are Normal


—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/abbaye/WpfHexEditorControl","title":"abbaye/WpfHexEditorControl","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/abbaye/WpfHexEditorControl"}},"updates":{"snippets":[{"icon":"PERSON","message":"@KaustubhPatange in #17: Hello, I cloned your sample again. Now its giving me Error while compiling. Here is an attachment of this! It says its Read Only File, but the thing is Attributes are Normal\r\n\r\n![attach](https://user-images.githubusercontent.com/22119598/33240828-b7ed0782-d2e2-11e7-8181-c3309e4c82e9.png)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/abbaye/WpfHexEditorControl/issues/17#issuecomment-347011691"}}}

**Comment by KaustubhPatange** [comment]
Did but won't working...

**Comment by abbaye** [comment]
I will check this when I'm at home in about 1 hours. But can you say me if wpf sample compile ?

The error are in winform sample only?

**Comment by KaustubhPatange** [comment]
Actually the error is in whole solution as I showed your the attachment image, it says Property cannot assigned to read only

**Comment by abbaye** [comment]
Get the last version ! it's work fine now.

I have lost to add 2 files in github lol ;)

**Comment by KaustubhPatange** [comment]
Yes.. It was saying resource designer and setting not available.. Thanks
for help!

**Comment by abbaye** [comment]
check now... :)

**Comment by KaustubhPatange** [comment]
Alright!

**Comment by KaustubhPatange** [comment]
Okay.. Now I have build the solution..the problem occur to implement in my project is we need to create an element host ...alright did it with creating a wpf user control then added hexeditor to it.. Then I selected element host as the wpf user control.. Alright I did it..but problem is there is no hexeditor.Filename i.e element host.Filename in my context.. I am not able to load any file to it..

**Comment by abbaye** [comment]
Did you have added all reference in project? Check sample for see reference you need

You can copy paste the code from sample in your project. It will be work ;) I have made external project to test and it's work.

**Comment by abbaye** [comment]
Are you ok ? Can you add control in you winform project?? Normally just drag and drop in form
