### ISSUE TITLE
Data virtualization

### ISSUE THREAD

**Issue by inbarbarkaiauroraview** [abbaye/WPFHexEditorControl#2]
Hi, 
Great project! Features just won't stop coming!

Is it possible to add data virtualization? I don't what the editor to load the whole file at once, only the parts that are visible to the user.

Thanks

**Comment by abbaye** [comment]
Thank  you sir :)
I add new features with suggestions like this

Just for sure :)

You want to load only a part file ?

This part can be modified/saved ?

Best regards


Le 5 févr. 2017 08:13, "Inbar Barkai" <notifications@github.com> a écrit :

Hi,
Great project! Features just won't stop coming!

Is it possible to add data virtualization? I don't what the editor to load
the whole file at once, only the parts that are visible to the user.

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/abbaye/WPFHexEditorControl/issues/2>, or mute the thread

**Comment by inbarbarkaiauroraview** [comment]
I want it to load the file as I scroll

**Comment by abbaye** [comment]
It's already like this

I need to uptimize refresh in wpf event

**Comment by inbarbarkaiauroraview** [comment]
Great! Thanks

**Comment by abbaye** [comment]
I will work on this soin as possible

Best Regards !




Le 5 févr. 2017 09:03, "Inbar Barkai" <notifications@github.com> a écrit :

Great! Thanks

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/abbaye/WPFHexEditorControl/issues/2#issuecomment-277521761>,
or mute the thread
