### ISSUE TITLE
Async data load

### ISSUE THREAD

**Issue by ghost** [abbaye/WpfHexEditorControl#6]
Hi,
Could you implement asynchronous data loading?
We are working against a custom stream and sometimes it takes a long time for it to read. While that happens the screen is frozen and it is impossible to show the user some progress indicator.

Thanks

**Comment by abbaye** [comment]
Hi  it' s possible but  I need time for that

I'm at the end of sessions at university

But you can check source code on github ;)

I Will check this on this summer

Best regards

Le 25 mai 2017 00:47, "Inbar Barkai" <notifications@github.com> a écrit :

Hi,
Could you implement asynchronous data loading?
We are working against a custom stream and sometimes it takes a long time
for it to read. While that happens the screen is frozen and it is
impossible to show the user some progress indicator.

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/abbaye/WPFHexEditorControl/issues/6>, or mute the thread
